spring:
  profiles:
    active: default
  application:
    name: microservicio-admin
  config:
    import: optional:configserver:http://localhost:8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Dirección del servidor Eureka
