spring:
  application:
    name: eureka-service
  config:
    import: optional:configserver:http://localhost:8081
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
